### ISSUE TITLE
Baseline 1

### ISSUE THREAD

**Issue by prashanththangavel** [Tixonmavrin/Zindi-Zimnat-Insurance-Recommendation-Challenge#1]
Hi @Tixonmavrin 
When I am trying to run Baseline 1, final submission has only 20000 rows. Am i missing something ?

**Comment by prashanththangavel** [comment]
![image](https://user-images.githubusercontent.com/34573777/89618770-65ab8180-d8aa-11ea-97d4-d7d60496b7de.png)

`y_test = pd.DataFrame(proba)
y_test.columns = le.inverse_transform(y_test.columns)`

when using predict proba i got 2D array (with 2 columns and 10k rows), so while inverse transforming it, 20k rows are resulted. Ideally we should be getting 21 columns while using predict proba, if im not wrong.

**Comment by Tixonmavrin** [comment]
<img width="691" alt="Снимок экрана 2020-08-07 в 16 58 51" src="https://user-images.githubusercontent.com/37590793/89653184-512db000-d8cf-11ea-91f3-94cae815c0a4.png">

**Comment by Tixonmavrin** [comment]
I will add my data

**Comment by garikhgh** [comment]
You worked hard man. good job
