### ISSUE TITLE
hyper parameters

### ISSUE THREAD

**Issue by garikhgh** [Tixonmavrin/Zindi-Zimnat-Insurance-Recommendation-Challenge#2]
hi. 
have you tried to use parameter tuning?
it might help

**Comment by Tixonmavrin** [comment]
It is just baseline. You can tune lightgbm (it is faster)

**Comment by Tixonmavrin** [comment]
https://www.kaggle.com/ilialar/hyperparameters-tunning-with-hyperopt

**Comment by garikhgh** [comment]
thanks

**Comment by Tixonmavrin** [comment]
It's my pleasure. And check https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html 
for controlling cross-validation. And check https://www.youtube.com/watch?v=g335THJxkto
